language:
  node_js
install:
  - npm i
  - npm i -g codecov
script:
  - npm run test:coverage
node_js:
  # - '4'
  - '6'
  - '8'
  - '10'
  - '12'
after_success:
  - npm run report-coverage
  - npm run success
